### ISSUE TITLE
Body polymorphism (closed edition)

### ISSUE THREAD

**Issue by glenjamin** [glenjamin/devcards-js#9]
We should aim to handle lots of different types of body, rendering appropriately.

Based on http://rigsomelight.com/devcards/#!/devdemos.extentions

Initially, this set of types is closed - a future enhancement will be allow open extensibility of supported types.

1. [x] `string` - markdown
2. [x] `number` - a number - see #6
3. [x] `array` - pretty and syntax highlighted - see #6
4. [x] `object` - pretty and syntax highlighted - see #6
5. [x] `regex` - pretty and syntax highlighted
    * [x] Include a little box you can type in that displays matches?
6. [x] `date` - ISO8601
7. [x] ES6 Map / Set - pretty and syntax highlighted - see #6
8. [x] ImmutableJS objects - pretty and syntax highlighted - see #6
9. [x] [ReactElement](http://facebook.github.io/react/docs/glossary.html#react-elements) - rendered
10. [x] `function` - is called, return value then handled as if it was passed - see #8
11. [x] `function(state)` - function is called, called again whenever state changes.
12. [x] [js-atom](https://github.com/cjohansen/js-atom) - value is rendered, re-rendered when it changes
    * Duck type anything with `deref` & `addWatch`

**Comment by glenjamin** [comment]
Started on this, WIP so far: ddc78a6

**Comment by glenjamin** [comment]
Syntax highlighting added in a8601c3

**Comment by glenjamin** [comment]
Built-in type checking libs i've found:

* https://www.npmjs.com/package/is-date-object
* https://www.npmjs.com/package/is-regexp
* https://www.npmjs.com/package/is-set
* https://www.npmjs.com/package/is-map
